### ISSUE TITLE
Library Not Available in Pip

### ISSUE THREAD

**Issue by fishyai** [onshape-public/python-client#1]
This library appears to not be available in pip. When I try to search in PyPI, it also doesn't come up. Any idea what's going on? Did the name of the package change?

Thanks a lot for putting this together!

**Comment by ethan92429** [comment]
Thanks for your interest! This library is not yet ready for public adoption. If you'd like to experiment with it, it is available under the PyPi test site [here](https://test.pypi.org/project/onshape-client/). Hope that helps and if you find some errors, please write up an issue here.

**Comment by ethan92429** [comment]
This library is in pip now. It is [here](https://pypi.org/project/onshape-client/).
